#!/bin/bash
# Gets patch notes for ARK: Survival Evolved and transmits them to Discord.
# Requires html2text.
# For automation add this line to your crontab: @hourly /full/path/to/arkpatchnotes >/dev/null 2>&1
# Change the workdir if you don't want to use the current location
workdir=$(pwd)
workdir="$workdir/.arkpatchnotes"
# Set your Discord webhook's url. Example: url="https://discordapp.com/api/webhooks/619303176143434675/SWYs1WVT568bx6qaCyWOPcYhO7IK-7L1IWjvfdsEgkZtDMbAj2KRwVids23"
discord_url=""
# Set to enable if you want also full patch notes to be saved locally
local_notes="disable"

[ -z "$(whereis html2text | awk '{print $2}')" ] && echo "html2text not found and needed for the script to work. Install it and then run the script again. Exiting." && exit 1

[ ! -d "$workdir" ] && mkdir "$workdir"

currentversion=$(curl -s "https://ark.gamepedia.com/Patch_Notes" | grep "PC -" | cut -d "=" -f 3 | sed "s/[^0-9.]//g")
lastversion=$(cat "$workdir/lastversion.txt")

[ "$lastversion" = "$currentversion" ] && exit 0

[ "$local_notes" = "enable" ] && \
curl -s "https://ark.gamepedia.com/$currentversion" | html2text | sed -n -e "/Released/,/PC_Patch/p" | grep -v "PC_Patch" > "$workdir/fullarkpatchnotes.txt"

echo "$currentversion" > "$workdir/lastversion.txt"
echo "ARK Update Released:" > "$workdir/arkpatchnotes.txt"
echo "Link: https://ark.gamepedia.com/$currentversion" >> "$workdir/arkpatchnotes.txt"
curl --data-binary "content"="$(<$workdir/arkpatchnotes.txt)" "$discord_url"
