#!/bin/bash
# Using netstat to create a graph of multiple incoming connections from an IP to make it possible to determine if your host is under DDOS attacks.
netstat -an|grep ESTABLISHED|awk '{print $5}'|awk -F: '{print $1}'|sort|uniq -c|awk '{ printf("%s\t%s\t",$2,$1); for (i = 0; i < $1; i++) {printf("*")}; print ""}'
